#name: Linux Build
#
#on:
#  release:
#    types: [published]
#  push:
#    tags:
#      - 'v*'
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  linux-build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Install Dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install build-essential
#          sudo apt-get install gcc-multilib g++-multilib
#
#      - name: Set up Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          profile: minimal
#          override: true
#
#      - name: Install i686 Target
#        run: rustup target add i686-unknown-linux-gnu
#
#      - name: Run Tests
#        run: |
#          cargo test --release --target x86_64-unknown-linux-gnu
#          cargo test --release --target i686-unknown-linux-gnu
#
#      - name: Create folder release
#        run: mkdir release
#
#      - name: Build Linux Binary x64
#        run: |
#          cargo build --release --target x86_64-unknown-linux-gnu
#          cp target/x86_64-unknown-linux-gnu/release/ssec release/ssec-x86_64-linux
#
#      - name: Build Linux Binary x32
#        run: |
#          cargo build --release --target i686-unknown-linux-gnu
#          cp target/i686-unknown-linux-gnu/release/ssec release/ssec-i686-linux
#
#      - name: Upload Linux Binaries
#        uses: actions/upload-artifact@v4
#        with:
#          name: linux-binaries
#          path: release/*
#
#      - name: Upload Linux Binary to Release
#        if: github.event_name == 'release'
#        uses: softprops/action-gh-release@v1
#        with:
#          files: ./release/ssec-x86_64-linux
#        env:
#          GITHUB_TOKEN: ${{ secrets.SSEC_TOKEN }}
#
#      - name: Upload x32 Binary to Release
#        if: github.event_name == 'release'
#        uses: softprops/action-gh-release@v1
#        with:
#          files: ./release/ssec-i686-linux
#        env:
#          GITHUB_TOKEN: ${{ secrets.SSEC_TOKEN }}
